-- 1. Bảng Khách Hàng
CREATE TABLE KHACHHANG (
    MaKH INTEGER PRIMARY KEY AUTOINCREMENT,
    Email TEXT NOT NULL UNIQUE,
    MatKhau TEXT NOT NULL,
    HoTen TEXT NOT NULL,
    SDT TEXT NOT NULL UNIQUE
);

-- 2. Bảng Loại Phòng
CREATE TABLE LOAIPHONG (
    MaLoai INTEGER PRIMARY KEY AUTOINCREMENT,
    TenLoai TEXT NOT NULL,
    GiaTien INTEGER NOT NULL, -- Dùng INTEGER vì tiền VNĐ không có số thập phân
    SoNguoiToiDa INTEGER NOT NULL
);

-- 3. Bảng Dịch Vụ
CREATE TABLE DICHVU (
    MaDV INTEGER PRIMARY KEY AUTOINCREMENT,
    TenDV TEXT NOT NULL,
    MoTa TEXT,
    GiaTien INTEGER NOT NULL,
    ThayDoiSL INTEGER NOT NULL DEFAULT 0, -- 0: false, 1: true (SQLite không có kiểu BOOLEAN)
    TrangThai TEXT NOT NULL DEFAULT 'Đang có', -- 'Đang có', 'Đang khóa'
    HinhAnh TEXT -- Lưu đường dẫn ảnh URL
);

-- 4. Bảng Nhân Viên
CREATE TABLE NHANVIEN (
    MaNV INTEGER PRIMARY KEY AUTOINCREMENT,
    MatKhau TEXT NOT NULL,
    HoTen TEXT NOT NULL,
    SDT TEXT NOT NULL UNIQUE,
    LaAdmin INTEGER NOT NULL DEFAULT 0 -- 0: Nhân viên, 1: Admin
);

-- 5. Bảng Hình Ảnh Loại Phòng (Phụ thuộc LOAIPHONG)
CREATE TABLE HINHANH_LOAIPHONG (
    MaAnh INTEGER PRIMARY KEY AUTOINCREMENT,
    MaLoai INTEGER NOT NULL,
    HinhAnh TEXT NOT NULL,
    FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai) ON DELETE CASCADE
);

-- 6. Bảng Phòng (Phụ thuộc LOAIPHONG)
CREATE TABLE PHONG (
    MaPhong INTEGER PRIMARY KEY AUTOINCREMENT,
    SoPhong TEXT NOT NULL UNIQUE,
    Tang INTEGER NOT NULL,
    MaLoai INTEGER NOT NULL,
    MoTa TEXT,
    TrangThai TEXT NOT NULL DEFAULT 'Sẵn sàng', -- 'Sẵn sàng', 'Bảo trì'
    FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai) ON DELETE RESTRICT
);

-- 7. Bảng Đặt Phòng (Phụ thuộc KHACHHANG, NHANVIEN)
CREATE TABLE DATPHONG (
    MaDP INTEGER PRIMARY KEY AUTOINCREMENT,
    MaKH INTEGER NOT NULL,
    TongTien INTEGER NOT NULL DEFAULT 0,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP, -- Tự động lấy ngày giờ hiện tại
    ThanhToan TEXT, -- Vd: 'Tiền mặt', 'Chuyển khoản'
    TrangThai TEXT NOT NULL DEFAULT 'Chờ xác nhận', -- 'Chờ xác nhận', 'Đã xác nhận', 'Đang lưu trú', 'Hoàn tất', 'Đã hủy'
    MaNV INTEGER, -- Cho phép NULL (Khách tự đặt)
    GhiChu TEXT,  -- Cho phép NULL
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH) ON DELETE RESTRICT,
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE SET NULL
);

-- 8. Bảng Chi Tiết Đặt Phòng (Phụ thuộc DATPHONG, PHONG, LOAIPHONG)
CREATE TABLE CHITIET_DATPHONG (
    MaCTDP INTEGER PRIMARY KEY AUTOINCREMENT,
    MaDP INTEGER NOT NULL,
    MaPhong INTEGER, -- Cho phép NULL (Lễ tân gán sau)
    MaLoai INTEGER NOT NULL,
    GiaPhong INTEGER NOT NULL,
    SoNguoi INTEGER NOT NULL,
    NgayNhan DATE NOT NULL,
    NgayTra DATE NOT NULL,
    TrangThai TEXT NOT NULL DEFAULT 'Chờ nhận', -- 'Chờ nhận', 'Đã nhận', 'Đã trả', 'Đã hủy'
    FOREIGN KEY (MaDP) REFERENCES DATPHONG(MaDP) ON DELETE CASCADE,
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong) ON DELETE SET NULL,
    FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai) ON DELETE RESTRICT
);

-- 9. Bảng Đặt Phòng - Dịch Vụ (Phụ thuộc CHITIET_DATPHONG, DICHVU)
CREATE TABLE DATPHONG_DICHVU (
    MaPDV INTEGER PRIMARY KEY AUTOINCREMENT,
    MaCTDP INTEGER NOT NULL,
    MaDV INTEGER NOT NULL,
    DonGia INTEGER NOT NULL,
    SoLuong INTEGER NOT NULL DEFAULT 1,
    Ngay DATE, -- Cho phép NULL
    Gio TIME,  -- Cho phép NULL
    TrangThai TEXT NOT NULL DEFAULT 'Chờ xử lý', -- 'Chờ xử lý', 'Đã phục vụ', 'Đã hủy'
    FOREIGN KEY (MaCTDP) REFERENCES CHITIET_DATPHONG(MaCTDP) ON DELETE CASCADE,
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV) ON DELETE RESTRICT
);